### ISSUE TITLE
Ohne Worte....

### ISSUE THREAD

**Issue by DavidBuss-lab** [kieran-btc/Robot-Wars#2]
Das kannst du nicht ernst meinen!!!!!
Wir haben hier ganz strikte Zeit Fenster und wir müssen das Spiel auf den Markt bringen. Und jetzt kommt so ein Scheiß. ES GIBT NICHT MAL EIN SPIELFELD. Wenn Chef das sieht wars das... Ich weis nicht was ich da noch sagen soll.
Liebe Grüße,
Dein guter Kollege David (;

**Comment by kieran028** [comment]
:(
